# Generated by Django 3.0.5 on 2020-05-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0002_auto_20200530_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário'},
        ),
    ]
