# Generated by Django 3.0.5 on 2020-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0004_solicitacao_concluida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data',
            field=models.DateField(blank=True, max_length=128, null=True, verbose_name='Data do atendimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='hora',
            field=models.TimeField(blank=True, max_length=128, null=True, verbose_name='Hora do atendimento'),
        ),
    ]
