# Generated by Django 3.0.3 on 2020-03-07 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('dataHora', models.DateTimeField(blank=True, max_length=128, null=True, verbose_name='Horario do comentario')),
                ('com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_noticias.Noticia')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_noticias.Pessoa')),
            ],
        ),
    ]
