# Generated by Django 3.0.3 on 2020-03-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0005_auto_20200306_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentari',
            new_name='noticia',
        ),
    ]
